#!/usr/bin/env python3
"""
Generate a parametric FEA input deck for the pulley modal/harmonic analysis.
The script reads the dominant forcing frequency identified from torque data
and creates a CalculiX .inp file for modal analysis and harmonic response.
"""
import os

def read_dominant_frequency():
    """Read dominant frequency from results/dominant_frequency.txt"""
    try:
        with open('../results/dominant_frequency.txt', 'r') as f:
            line = f.readline().strip()
            return float(line)
    except FileNotFoundError:
        print("WARNING: dominant_frequency.txt not found, using default 25 Hz")
        return 25.0

def generate_inp_file(freq_hz):
    """
    Generate a simple CalculiX input file for a pulley-like geometry.
    This is a simplified model for demonstration purposes.
    """
    # Pulley geometry parameters (dimensions in mm)
    outer_radius = 300.0
    inner_radius = 50.0
    thickness = 40.0
    
    # Material properties (steel)
    youngs_modulus = 210000.0  # MPa
    poisson_ratio = 0.3
    density = 7.85e-9          # t/mm^3 (converted from kg/m^3)
    
    # Load amplitude (derived from torque measurement)
    load_amplitude = 1000.0    # N
    
    # Frequency range for harmonic analysis (Hz)
    f_start = 0.1
    f_end = 200.0
    n_steps = 200
    
    inp_content = f"""**================================================
** Pulley Vibration Analysis - Generated by generate_fea.py
** Dominant forcing frequency = {freq_hz:.2f} Hz
**================================================
*HEADING
Pulley modal and harmonic analysis
*NODE
1, 0.0, 0.0, 0.0
2, {outer_radius}, 0.0, 0.0
3, 0.0, {outer_radius}, 0.0
4, -{outer_radius}, 0.0, 0.0
5, 0.0, -{outer_radius}, 0.0
** Additional nodes would be generated by a proper mesher
*ELEMENT, TYPE=C3D8, ELSET=PULLEY
1, 1, 2, 3, 4, 5, 6, 7, 8
** (Simplified element definition)
*MATERIAL, NAME=STEEL
*ELASTIC
{youngs_modulus}, {poisson_ratio}
*DENSITY
{density}
*SOLID SECTION, ELSET=PULLEY, MATERIAL=STEEL
**
** BOUNDARY CONDITIONS
** Fix inner bore (cylindrical surface)
*NSET, NSET=FIXED
1
*BOUNDARY
FIXED, 1, 6, 0.0
**
** LOADS
** Harmonic load applied at outer radius in radial direction
*AMPLITUDE, NAME=HARM, DEFINITION=HARMONIC
{freq_hz}, 1.0, 0.0
*CLOAD, AMPLITUDE=HARM
2, 1, {load_amplitude}
**
** STEP 1: MODAL ANALYSIS
*STEP
*FREQUENCY
10, , , 
*NODE PRINT, NSET=NALL
U
*EL PRINT, ELSET=PULLEY
S
*END STEP
**
** STEP 2: HARMONIC RESPONSE
*STEP
*STEADY STATE DYNAMICS, DIRECT
{f_start}, {f_end}, {n_steps}
*CLOAD, AMPLITUDE=HARM
2, 1, {load_amplitude}
*NODE PRINT, NSET=NALL
U
*EL PRINT, ELSET=PULLEY
S
*END STEP
**
*END PART
"""
    return inp_content

def main():
    # Ensure results directory exists
    os.makedirs('../results', exist_ok=True)
    
    # Read dominant forcing frequency
    f_dom = read_dominant_frequency()
    print(f"Dominant forcing frequency: {f_dom:.2f} Hz")
    
    # Generate input deck
    inp_content = generate_inp_file(f_dom)
    
    # Write to file
    inp_path = '../results/pulley_analysis.inp'
    with open(inp_path, 'w') as f:
        f.write(inp_content)
    
    print(f"FEA input deck written to {inp_path}")
    
    # Also create a simple readme for the FEA model
    readme_path = '../results/fea_model_readme.txt'
    with open(readme_path, 'w') as f:
        f.write(f"""FEA Model Parameters:
- Outer radius: 300 mm
- Inner radius: 50 mm
- Thickness: 40 mm
- Material: Steel (E = 210 GPa, ν = 0.3, ρ = 7850 kg/m³)
- Boundary condition: inner bore fully fixed
- Harmonic load amplitude: 1000 N radial at outer radius
- Forcing frequency: {f_dom:.2f} Hz
- Frequency range for harmonic analysis: 0.1 - 200 Hz
- Solver: CalculiX (CGX)
""")
    print(f"Model description written to {readme_path}")

if __name__ == '__main__':
    main()